version: 2.1
jobs:
  build:
    docker:
      - image: cimg/python:3.10
    environment:
      CC_TEST_REPORTER_ID: 2e0d5e39-aebd-44d3-be34-34541e0f9d66
    steps:
      - checkout
      - run:
          name: Setup Code Climate test-reporter
          command: |
              # download test reporter as a static binary
              curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
              chmod +x ./cc-test-reporter
              ./cc-test-reporter before-build
      - run:
          name: Install Pip
          command: |
            python3.10 -m ensurepip --default-pip
            python3.10 -m pip install --upgrade pip==23.2.1
      - run:
          name: Install dependencies
          command: pip install -r requirements.txt
      - run:
          name: Running Tests
          command: coverage run -m unittest && coverage xml && coverage report -m
      - run:
          name: Update CodeClimate coverage report
          command: |
              ./cc-test-reporter after-build